# Generated by Django 4.2.7 on 2023-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('annual_co2_emissions_tonnes', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Carbon',
                'ordering': ('country',),
            },
        ),
    ]
